framework:
    default_locale: fr
    translator:
        default_path: '%kernel.project_dir%/translations'
        fallbacks:
            - fr

    secret: '%env(APP_SECRET)%'
    http_method_override: false
    csrf_protection:
        enabled: true

    # Configuration des sessions
    session:
        # Session pour prod

        #enabled: true
        #handler_id: session.handler.pdo
        #cookie_lifetime: 5184000
        #gc_maxlifetime: 5184000
        #storage_factory_id: session.storage.factory.native

        handler_id: null
        cookie_secure: auto
        cookie_samesite: lax
        storage_factory_id: session.storage.factory.native
        cookie_lifetime: 31536000   # 1 an en secondes
        gc_maxlifetime: 31536000    # 1 an en secondes

    php_errors:
        log: true

when@test:
    framework:
        test: true
        session:
            storage_factory_id: session.storage.factory.mock_file
