security:
    enable_authenticator_manager: true
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: number

    firewalls:
        main:
            provider: app_user_provider
            custom_authenticator: App\Security\OTPAuthenticator
            form_login:
                enable_csrf: true
            entry_point: App\Security\OTPAuthenticator
            logout:
                path: app_logout
                target: app_home
            access_denied_url: app_home

    access_control:
        - { path: ^/admin, roles: ROLE_ADMIN }

when@test:
    security:
        password_hashers:
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4
                time_cost: 3
                memory_cost: 10
